---
title: "Multiple_regression_duration"
author: "Sørine"
date: "2023-01-11"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(gvlma) #For assessing linear model assumptions. 
library(car)
library(writexl)
library(readxl)
library(lme4)
library(lmerTest)
library(knitr)
library(MASS)
library(codingMatrices)
#install.packages("gt")
#install.packages("AICcmodavg")
#install.packages("gtsummary")
library(AICcmodavg)
library(gt)
library(gtsummary)

```

```{r}
df_phen_event <- read.csv("Data/Piecewise_regression_temperature/piecewise_temp_air.csv", sep=",",stringsAsFactors = FALSE, header = TRUE)

df8 <- read.csv("Data/Dataset_for_GAM_NEW\\duration.csv", sep=",",stringsAsFactors = FALSE, header = TRUE)

dfsnowmelt_climatestation <- readxl::read_xlsx("Data/Climate_data_Zackenberg/Snowmelt_climatestation.xlsx")

```

Match dataframes

```{r}
df_phen_event$Snowmelt <- dfsnowmelt_climatestation$DOY[match(paste0(df_phen_event$Year),
                                                              paste0(dfsnowmelt_climatestation$Year))]

```

```{r}
df_Acari <- subset(df_phen_event,SpeciesID=="Acari")
df_Acari%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Acari
df_Acari <- subset(df_Acari, df_Acari$Plot!= "Art1")

unique(df_Acari$Plot)

df_Acari$Plot <- as.factor(df_Acari$Plot)


#mycontrasts = contrasts(df_CHCE$Plot)

#S <- cbind(1, contrasts(df_CHCE$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 1/2, 1/2, -1/2, 0, -1/2)
H2 = c(-1, 1/2, 1/2, 0, 0, 0)
H3 = c(1, 0, 0, -1/2, 0, -1/2)
H4 = c(-1/5, -1/5, -1/5, -1/5, 1, -1/5)
L <- rbind(H1, H2, H4) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Acari$Plot) <- S
contrasts(df_Acari$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Acari)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Acari)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Acari)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Acari)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)

```

```{r}
ancova_acari <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_acari, format = "pandoc", digits = 3)
```

```{r}
df_Acari <- subset(df_phen_event,SpeciesID=="Acari")
df_Acari%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Acari
df_Acari <- subset(df_Acari, df_Acari$Plot!= "Art1")

unique(df_Acari$Plot)

df_Acari$Plot <- as.factor(df_Acari$Plot)


#mycontrasts = contrasts(df_CHCE$Plot)

#S <- cbind(1, contrasts(df_CHCE$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 1/2, 1/2, -1/2, 0, -1/2)
H2 = c(-1, 1/2, 1/2, 0, 0, 0)
H3 = c(1, 0, 0, -1/2, 0, -1/2)
H4 = c(-1/5, -1/5, -1/5, -1/5, 1, -1/5)
L <- rbind(H1, H3, H4) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Acari$Plot) <- S
contrasts(df_Acari$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Acari)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Acari)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Acari)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Acari)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)

```

```{r}
ancova_acari <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_acari, format = "pandoc", digits = 3)
```


```{r message=FALSE, results='asis'}
df_Collembola <- subset(df_phen_event,SpeciesID=="Collembola")
df_Collembola%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Collembola
df_Collembola <- subset(df_Collembola, df_Collembola$Plot!= "Art1")

unique(df_Collembola$Plot)

df_Collembola$Plot <- as.factor(df_Collembola$Plot)


#mycontrasts = contrasts(df_CHCE$Plot)

#S <- cbind(1, contrasts(df_CHCE$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 1/2, 1/2, -1/2, 0, -1/2)
H2 = c(-1, 1/2, 1/2, 0, 0, 0)
H3 = c(1, 0, 0, -1/2, 0, -1/2)
H4 = c(-1/5, -1/5, -1/5, -1/5, 1, -1/5)
L <- rbind(H1, H2, H4) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Collembola$Plot) <- S
contrasts(df_Collembola$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Collembola)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Collembola)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Collembola)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Collembola)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm2)

```

```{r}
ancova_collem <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_collem, format = "pandoc", digits = 3)
```


```{r message=FALSE, results='asis'}
df_Collembola <- subset(df_phen_event,SpeciesID=="Collembola")
df_Collembola%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Collembola
df_Collembola <- subset(df_Collembola, df_Collembola$Plot!= "Art1")

unique(df_Collembola$Plot)

df_Collembola$Plot <- as.factor(df_Collembola$Plot)


#mycontrasts = contrasts(df_CHCE$Plot)

#S <- cbind(1, contrasts(df_CHCE$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 1/2, 1/2, -1/2, 0, -1/2)
H2 = c(-1, 1/2, 1/2, 0, 0, 0)
H3 = c(1, 0, 0, -1/2, 0, -1/2)
H4 = c(-1/5, -1/5, -1/5, -1/5, 1, -1/5)
L <- rbind(H1, H3, H4) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Collembola$Plot) <- S
contrasts(df_Collembola$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Collembola)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Collembola)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Collembola)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Collembola)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm2)

```

```{r}
ancova_collem <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_collem, format = "pandoc", digits = 3)
```


```{r}
df_APHI <- subset(df_phen_event,SpeciesID=="Aphidoidea")
df_APHI%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_APHI

multiple_lm <- lm(Duration ~ Snowmelt+Onset_Temp+Year, df_APHI)

summary(multiple_lm, digits = 3)

```


```{r}
df_Cocco <- subset(df_phen_event,SpeciesID=="Coccoidea")
df_Cocco%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Cocco

unique(df_Cocco$Plot)

df_Cocco$Plot <- as.factor(df_Cocco$Plot)


#mycontrasts = contrasts(df_CHCE$Plot)

#S <- cbind(1, contrasts(df_CHCE$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(1/2, 1/2, -1/2, -1/2)
L <- rbind(H1) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Cocco$Plot) <- S
contrasts(df_Cocco$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Cocco)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Cocco)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Cocco)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Cocco)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm4)
```

```{r}
ancova_cocco <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_cocco, format = "pandoc", digits = 3)
```


```{r}
df_CHCE <- subset(df_phen_event,SpeciesID=="CHCE")
df_CHCE%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_CHCE

unique(df_CHCE$Plot)

df_CHCE$Plot <- as.factor(df_CHCE$Plot)


#mycontrasts = contrasts(df_CHCE$Plot)

#S <- cbind(1, contrasts(df_CHCE$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 0, 1/2, 1/2, -1/2, 0, -1/2)
H2 = c(0, -1, 1/2, 1/2, 0, 0, 0)
H3 = c(0, 1, 0, 0, -1/2, 0, -1/2)
H4 = c(-1/6, -1/6, -1/6, -1/6, -1/6, 1, -1/6)
H5 = c(1, -1/6, -1/6, -1/6, -1/6, -1/6, -1/6)
L <- rbind(H1, H2, H4, H5) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_CHCE$Plot) <- S
contrasts(df_CHCE$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_CHCE)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_CHCE)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_CHCE)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_CHCE)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)

```

```{r}
ancova_CHCE <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_CHCE, format = "pandoc", digits = 3)
```


```{r}
df_CHCE <- subset(df_phen_event,SpeciesID=="CHCE")
df_CHCE%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_CHCE

unique(df_CHCE$Plot)

df_CHCE$Plot <- as.factor(df_CHCE$Plot)


#mycontrasts = contrasts(df_CHCE$Plot)

#S <- cbind(1, contrasts(df_CHCE$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 0, 1/2, 1/2, -1/2, 0, -1/2)
H2 = c(0, -1, 1/2, 1/2, 0, 0, 0)
H3 = c(0, 1, 0, 0, -1/2, 0, -1/2)
H4 = c(-1/6, -1/6, -1/6, -1/6, -1/6, 1, -1/6)
H5 = c(1, -1/6, -1/6, -1/6, -1/6, -1/6, -1/6)
L <- rbind(H1, H3, H4, H5) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_CHCE$Plot) <- S
contrasts(df_CHCE$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_CHCE)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_CHCE)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_CHCE)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_CHCE)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)

```

```{r}
ancova_CHCE <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_CHCE, format = "pandoc", digits = 3)
```


```{r}
df_ANMU <- subset(df_phen_event,SpeciesID=="ANMU")
df_ANMU%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_ANMU

unique(df_ANMU$Plot)

df_ANMU$Plot <- as.factor(df_ANMU$Plot)


#mycontrasts = contrasts(df_ANMU$Plot)

#S <- cbind(1, contrasts(df_ANMU$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 0, 1/2, 1/2, -1/2, 0, -1/2)
H2 = c(0, -1, 1/2, 1/2, 0, 0, 0)
H3 = c(0, 1, 0, 0, -1/2, 0, -1/2)
H4 = c(-1/6, -1/6, -1/6, -1/6, -1/6, 1, -1/6)
H5 = c(1, -1/6, -1/6, -1/6, -1/6, -1/6, -1/6)
L <- rbind(H1, H2, H4, H5) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_ANMU$Plot) <- S
contrasts(df_ANMU$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_ANMU)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_ANMU)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_ANMU)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_ANMU)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm2)
```

```{r}
ancova_ANMU <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_ANMU, format = "pandoc", digits = 3)
```


```{r}
df_ANMU <- subset(df_phen_event,SpeciesID=="ANMU")
df_ANMU%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_ANMU

unique(df_ANMU$Plot)

df_ANMU$Plot <- as.factor(df_ANMU$Plot)


#mycontrasts = contrasts(df_ANMU$Plot)

#S <- cbind(1, contrasts(df_ANMU$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 0, 1/2, 1/2, -1/2, 0, -1/2)
H2 = c(0, -1, 1/2, 1/2, 0, 0, 0)
H3 = c(0, 1, 0, 0, -1/2, 0, -1/2)
H4 = c(-1/6, -1/6, -1/6, -1/6, -1/6, 1, -1/6)
H5 = c(1, -1/6, -1/6, -1/6, -1/6, -1/6, -1/6)
L <- rbind(H1, H3, H4, H5) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_ANMU$Plot) <- S
contrasts(df_ANMU$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_ANMU)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_ANMU)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_ANMU)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_ANMU)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm2)
```

```{r}
ancova_ANMU <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_ANMU, format = "pandoc", digits = 3)
```

```{r}
df_Culli <- subset(df_phen_event,SpeciesID=="Culicidae")
df_Culli%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Culli

multiple_lm <- lm(Duration ~ Snowmelt+Onset_Temp+Year, df_Culli)

summary(multiple_lm)
```


```{r}
df_MYSC <- subset(df_phen_event,SpeciesID=="MYSC")
df_MYSC%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_MYSC

unique(df_MYSC$Plot)

df_MYSC$Plot <- as.factor(df_MYSC$Plot)


#mycontrasts = contrasts(df_ANMU$Plot)

#S <- cbind(1, contrasts(df_ANMU$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 0, 1/2, 1/2, -1/2, -1/2)
H2 = c(0, -1, 1/2, 1/2, 0, 0)
H3 = c(0, 1, 0, 0, -1/2, -1/2)
H5 = c(1, -1/5, -1/5, -1/5, -1/5, -1/5)
L <- rbind(H1, H2, H5) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_MYSC$Plot) <- S
contrasts(df_MYSC$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_MYSC)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_MYSC)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_MYSC)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_MYSC)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm3)
```

```{r}
ancova_MYSC <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
ancova_MYSC

options(knitr.kable.NA = '')
kable(ancova_MYSC, format = "pandoc", digits = 3)
```

```{r}
df_MYSC <- subset(df_phen_event,SpeciesID=="MYSC")
df_MYSC%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_MYSC

unique(df_MYSC$Plot)

df_MYSC$Plot <- as.factor(df_MYSC$Plot)


#mycontrasts = contrasts(df_ANMU$Plot)

#S <- cbind(1, contrasts(df_ANMU$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(0, 0, 1/2, 1/2, -1/2, -1/2)
H2 = c(0, -1, 1/2, 1/2, 0, 0)
H3 = c(0, 1, 0, 0, -1/2, -1/2)
H5 = c(1, -1/5, -1/5, -1/5, -1/5, -1/5)
L <- rbind(H1, H3, H5) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_MYSC$Plot) <- S
contrasts(df_MYSC$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_MYSC)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_MYSC)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_MYSC)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_MYSC)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm3)
```

```{r}
df_Phori <- subset(df_phen_event,SpeciesID=="Phoridae")
df_Phori%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Phori

unique(df_Phori$Plot)

df_Phori$Plot <- as.factor(df_Phori$Plot)


#mycontrasts = contrasts(df_ANMU$Plot)

#S <- cbind(1, contrasts(df_ANMU$Plot))
#L <- ginv(S)
#L %>% fractions()
H1 = c(1, -1/2, -1/2)
L <- rbind(H1) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Phori$Plot) <- S
contrasts(df_Phori$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Phori)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Phori)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Phori)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Phori)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)
```
```{r}
ancova_Phori <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_Phori, format = "pandoc", digits = 3)
```


```{r}
df_Liny <- subset(df_phen_event,SpeciesID=="Linyphiidae")
df_Liny%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Liny
df_Liny <- subset(df_Liny, df_Liny$Plot!= "Art1")
df_Liny <- subset(df_Liny, df_Liny$Plot!= "Art6")

df_Liny$Plot <- as.factor(df_Liny$Plot)

H1 = c(0, 1/2, 1/2, -1/2, -1/2)
H2 = c(-1, 1/2, 1/2, 0, 0)
H3 = c(1, 0, 0, -1/2, -1/2)
#H4 = c(-1/5, -1/5, -1/5, -1/5, 1, -1/5)
L <- rbind(H1, H2) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Liny$Plot) <- S
contrasts(df_Liny$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Liny)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Liny)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Liny)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Liny)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)
```

```{r}
ancova_Liny <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_Liny, format = "pandoc", digits = 3)
```

```{r}
df_Liny <- subset(df_phen_event,SpeciesID=="Linyphiidae")
df_Liny%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Liny
df_Liny <- subset(df_Liny, df_Liny$Plot!= "Art1")
df_Liny <- subset(df_Liny, df_Liny$Plot!= "Art6")

df_Liny$Plot <- as.factor(df_Liny$Plot)

H1 = c(0, 1/2, 1/2, -1/2, -1/2)
H2 = c(-1, 1/2, 1/2, 0, 0)
H3 = c(1, 0, 0, -1/2, -1/2)
#H4 = c(-1/5, -1/5, -1/5, -1/5, 1, -1/5)
L <- rbind(H1, H3) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Liny$Plot) <- S
contrasts(df_Liny$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Liny)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Liny)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Liny)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Liny)

ggplot(df_Liny, aes(Snowmelt,Duration, color = Plot))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)
```

```{r}
ancova_Liny <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_Liny, format = "pandoc", digits = 3)
```

```{r}
df_Lyco <- subset(df_phen_event,SpeciesID=="Lycosidae")
df_Lyco%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Lyco
df_Lyco <- subset(df_Lyco, df_Lyco$Plot!= "Art1")

df_Lyco$Plot <- as.factor(df_Lyco$Plot)

H1 = c(0, 1/2, 1/2, -1/2, -1/2)
H2 = c(-1, 1/2, 1/2, 0, 0)
H3 = c(1, 0, 0, -1/2, -1/2)
L <- rbind(H1, H2) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Lyco$Plot) <- S
contrasts(df_Lyco$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Lyco)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Lyco)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Lyco)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Lyco)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)
```

```{r}
ancova_Lyco <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_Lyco, format = "pandoc", digits = 3)
```

```{r}
df_Lyco <- subset(df_phen_event,SpeciesID=="Lycosidae")
df_Lyco%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Lyco
df_Lyco <- subset(df_Lyco, df_Lyco$Plot!= "Art1")

df_Lyco$Plot <- as.factor(df_Lyco$Plot)

H1 = c(0, 1/2, 1/2, -1/2, -1/2)
H2 = c(-1, 1/2, 1/2, 0, 0)
H3 = c(1, 0, 0, -1/2, -1/2)
L <- rbind(H1, H3) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Lyco$Plot) <- S
contrasts(df_Lyco$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Lyco)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Lyco)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Lyco)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Lyco)


#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)
```

```{r}
ancova_Lyco <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_Lyco, format = "pandoc", digits = 3)
```


```{r}
df_Thomi <- subset(df_phen_event,SpeciesID=="Thomisidae")
df_Thomi%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Thomi

multiple_lm <- lm(Duration ~ Snowmelt+Onset_Temp+Year, df_Thomi)

summary(multiple_lm)
```


```{r}
df_Ich <- subset(df_phen_event,SpeciesID=="Ichneumonidae")
df_Ich%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Ich

df_Ich$Plot <- as.factor(df_Ich$Plot)


H1 = c(0, 0, 1/2, 1/2, -1/2, -1/2)
H2 = c(0, -1, 1/2, 1/2, 0, 0)
H3 = c(0, 1, 0, 0, -1/2, -1/2)
H5 = c(1, -1/5, -1/5, -1/5, -1/5, -1/5)
L <- rbind(H1, H2, H5) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Ich$Plot) <- S
contrasts(df_Ich$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Ich)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Ich)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Ich)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Ich)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm2)
```

```{r}
ancova_Ich <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_Ich, format = "pandoc", digits = 3)
```

```{r}
df_Ich <- subset(df_phen_event,SpeciesID=="Ichneumonidae")
df_Ich%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Ich

df_Ich$Plot <- as.factor(df_Ich$Plot)

H1 = c(0, 0, 1/2, 1/2, -1/2, -1/2)
H2 = c(0, -1, 1/2, 1/2, 0, 0)
H3 = c(0, 1, 0, 0, -1/2, -1/2)
H5 = c(1, -1/5, -1/5, -1/5, -1/5, -1/5)
L <- rbind(H1, H3, H5) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Ich$Plot) <- S
contrasts(df_Ich$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Ich)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Ich)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Ich)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Ich)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm2)
```

```{r}
ancova_Ich <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_Ich, format = "pandoc", digits = 3)
```


```{r}
df_Chal <- subset(df_phen_event,SpeciesID=="Chalcidoidea")
df_Chal%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Chal

df_Chal$Plot <- as.factor(df_Chal$Plot)

H1 = c(1/2, 1/2, -1)
L <- rbind(H1) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Chal$Plot) <- S
contrasts(df_Chal$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Chal)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Chal)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Chal)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Chal)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm1)
```

```{r}
ancova_Chal <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_Chal, format = "pandoc", digits = 3)
```

```{r}
df_Nymph <- subset(df_phen_event,SpeciesID=="Nymphalidae")
df_Nymph%>%
  subset(!is.na(Onset_Temp)&!is.na(Onset)) -> df_Nymph

df_Nymph$Plot <- as.factor(df_Nymph$Plot)

H1 = c(1/2, 1/2, -1)
L <- rbind(H1) # bind the rows together
L %>% fractions()
S <- ginv(L) # compute the inverse
S 

contrasts(df_Nymph$Plot) <- S
contrasts(df_Nymph$Plot)

multiple_lm1 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year, df_Nymph)
multiple_lm2 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot, df_Nymph)
multiple_lm3 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Onset_Temp:Plot, df_Nymph)
multiple_lm4 <- lm(Duration ~ Snowmelt+Onset_Temp+Plot+Year+Snowmelt:Plot+Onset_Temp:Plot, df_Nymph)

#AIC(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)
models <- list(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

model.names <- c('multiple_lm1', 'multiple_lm2', 'multiple_lm3', 'multiple_lm4')

gt(aictab(cand.set = models, modnames = model.names))

tbl_regression(multiple_lm1)
tbl_regression(multiple_lm2)
tbl_regression(multiple_lm3)
tbl_regression(multiple_lm4)

summary(multiple_lm2)
```

```{r}
ancova_nymph <- anova(multiple_lm1, multiple_lm2, multiple_lm3, multiple_lm4)

options(knitr.kable.NA = '')
kable(ancova_nymph, format = "pandoc", digits = 3)
```
